name: CI Gradle

on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Artefact-Version:
    runs-on: ubuntu-latest
    outputs:
      RELEASED_VERSION: ${{ steps.vars.outputs.RELEASED_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: vars
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG_NAME#v}"
          echo "RELEASED_VERSION=$VERSION" >> $GITHUB_OUTPUT

  Build:
    needs: [Artefact-Version]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current

      - name: Gradle Build and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ needs.Artefact-Version.outputs.RELEASED_VERSION }}

          gradle build publish \
            -DAPI_SPEC_VERSION=$VERSION \
            -DGITHUB_REPOSITORY=${{ github.repository }} \
            -DGITHUB_ACTOR=${{ github.actor }} \
            -DGITHUB_TOKEN=$GITHUB_TOKEN

      - name: Upload JAR Artefact
        uses: actions/upload-artifact@v4
        if: github.event_name == 'push'
        env:
          GITHUB_REPO: ${{ github.repository##*/ }}
        with:
          name: app-jar
          path: build/libs/${GITHUB_REPO}-${{ needs.Artefact-Version.outputs.draft_version }}.jar

  Build-Docker:
    needs: [ Build ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download JAR Artefact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/libs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}:${{ needs.Artefact-Version.outputs.RELEASED_VERSION }}
            ghcr.io/${{ github.repository }}:latest
          build-args: |
            BASE_IMAGE=openjdk:21-jdk-slim
            JAR_FILE_NAME=${{ github.repository }}:${{ needs.Artefact-Version.outputs.RELEASED_VERSION }}

#        - name: Log in to Azure Container Registry
#          uses: docker/login-action@v3
#          with:
#            registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
#            username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
#            password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
#
#        - name: Build and Push Docker Image to GitHub & Azure
#          uses: docker/build-push-action@v6
#          with:
#            context: .
#            file: Dockerfile
#            push: true
#            tags: |
#              ghcr.io/${{ github.repository }}:${{ needs.Artefact-Version.outputs.RELEASED_VERSION }}
#              ghcr.io/${{ github.repository }}:latest
#              ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/${{ github.repository }}:${{ needs.Artefact-Version.outputs.draft_version }}
#              ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/${{ github.repository }}:latest
#            build-args: |
#              BASE_IMAGE=ghcr.io/hmcts/java:21-jdk-slim
#              JAR_FILE_NAME=${{ github.repository }}:${{ needs.Artefact-Version.outputs.draft_version }}

