name: Contract Tests Provider

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

env:
  is_release: false

jobs:
  Artefact-Version:
    runs-on: ubuntu-latest
    outputs:
      artefact_version: ${{  env.is_release && steps.artefact.outputs.release_version || steps.artefact.outputs.draft_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Artefact Version
        id: artefact
        uses: hmcts/artefact-version-action@v1
        with:
          release: ${{ env.is_release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Provider-Tests:
    needs: [ Artefact-Version ]
    runs-on: ubuntu-latest
    env:
      ARTEFACT_VERSION: ${{ needs.Artefact-Version.outputs.artefact_version }}
      PACT_BROKER_URL: https://hmcts-dts.pactflow.io
      PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
      PACT_VERIFIER_PUBLISH_RESULTS: true
      GIT_COMMIT: ${{ github.sha }}
      GIT_BRANCH: ${{ github.ref_name }}
      PACT_ENV: dev/pactTest
      PACT_APPLICATION_NAME: CPRefDataJudgesProvider
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current

      - name: Pact Provider Verification
        env:
          ARTEFACT_VERSION: ${{ needs.Artefact-Version.outputs.artefact_version }}
          GIT_BRANCH: ${{ github.ref_name }}
          PACT_BROKER_URL: ${{ env.PACT_BROKER_URL }}
          PACT_BROKER_HOST: hmcts-dts.pactflow.io
          PACT_BROKER_TOKEN: ${{ env.PACT_BROKER_TOKEN }}
          PACT_ENV: ${{ env.PACT_ENV }}
        run: |
          echo "ARTEFACT_VERSION=$ARTEFACT_VERSION"
          echo "GIT_BRANCH=$GIT_BRANCH"
          echo "PACT_BROKER_URL=$PACT_BROKER_URL"
          echo "PACT_ENV=$PACT_ENV"
          echo "PACT_BROKER_HOST=$PACT_BROKER_HOST"
          
          # Run provider verification
          gradle pactVerificationTest \
            -Dpact.provider.version="$ARTEFACT_VERSION" \
            -Dpact.verifier.publishResults=true \
            -Dpact.provider.branch="$GIT_BRANCH" \
            -Dpact.broker.token="$PACT_BROKER_TOKEN" \
            -Dpact.broker.url="$PACT_BROKER_URL" \
            -Dpact.env="$PACT_ENV"

      # https://github.com/pactflow/actions
      - uses: pactflow/actions/create-or-update-version@v2
        with:
          application_name: ${{ env.PACT_APPLICATION_NAME }}
          version: ${{ needs.Artefact-Version.outputs.artefact_version }}
          broker_url: ${{ env.PACT_BROKER_URL }}
          token: ${{ env.PACT_BROKER_TOKEN }}
          branch: ${{ env.GIT_BRANCH }}

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Pact CLI
        run: npm install -g @pact-foundation/pact-cli

      - name: Can I Deploy
        env:
          PACT_BROKER_URL: ${{ env.PACT_BROKER_URL }}
          GIT_COMMIT: ${{ github.sha }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
          PACT_ENV: ${{ env.PACT_ENV }}
        run: |
          pact-broker can-i-deploy \
            --pacticipant "CPRefDataJudgesProvider" \
            --version "$GIT_COMMIT" \
            --to-environment "$PACT_ENV" \
            --broker-base-url "$PACT_BROKER_URL" \
            --broker-token "$PACT_BROKER_TOKEN" \
            --output table
          can_i_deploy_status=$?
          if [ "$can_i_deploy_status" -ne 0 ]; then
            echo "❌ Can-I-Deploy failed — this version is NOT safe to deploy to $PACT_ENV - (deploy statue: $can_i_deploy_status)"
            exit 1
          else
            echo "✅ Can-I-Deploy succeeded — this version is safe to deploy to $PACT_ENV."
          fi

#      - uses: pactflow/actions/can-i-deploy@v2
#        with:
#          application_name: ${{ env.PACT_APPLICATION_NAME }}
#          version: ${{ needs.Artefact-Version.outputs.artefact_version }}
#          broker_url: ${{ env.PACT_BROKER_URL }}
#          token: ${{ env.PACT_BROKER_TOKEN }}
#          to: ${{ env.PACT_ENV }}
#          retry_while_unknown: 4
#          retry_interval: 20
