name: GH API (temp)

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger ADO pipeline with gh api
        env:
          GH_TOKEN: ${{ github.token }}
          ADO_PAT: ${{ secrets.HMCTS_ADO_PAT }}
        run: |
          cat <<EOF | gh api \
            --method POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic $(echo -n ":$ADO_PAT" | base64)" \
            https://dev.azure.com/hmcts-cpp/cpp-apps/_apis/pipelines/cp-gh-artifact-to-acr/runs?api-version=7.0 \
            --input -
      {
        "resources": {
          "repositories": {
            "self": {
              "refName": "refs/heads/main"
            }
          }
        },
        "templateParameters": {
          "GROUP_ID": "uk.gov.hmcts.cp",
          "ARTIFACT_ID": "hmcts/service-cp-refdata-courthearing-judges",
          "ARTIFACT_VERSION": "0.0.999-TESTING-ONLY"
        }
      }
      EOF
