name: Run Provider Pact Publish Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-provider-pacts:
    runs-on: ubuntu-latest

    env:
      PACT_BROKER_URL: https://hmcts-dts.pactflow.io
      PACT_BROKER_HOST: hmcts-dts.pactflow.io
      PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
      PACT_VERIFIER_PUBLISH_RESULTS: true
      GIT_COMMIT: ${{ github.sha }}
      GIT_BRANCH: ${{ github.ref_name }}
      PACT_ENV: dev/pactTest


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Install Pact CLI
        run: npm install -g @pact-foundation/pact-cli

      - name: Make provider script executable
        run: chmod +x publish-pacts.sh

      - name: Run provider publish script
        run: ./publish-pacts.sh